In [1]:
import numpy

In [3]:
array1 = numpy.array([2,3,5,7,11,13,15,17,19,23,29,31])

In [5]:
array1

array([ 2,  3,  5,  7, 11, 13, 15, 17, 19, 23, 29, 31])

In [13]:
type(array1)

numpy.ndarray

* narray -> n차원 배열이라는뜻

In [14]:
array1.shape

(12,)

* 왜 12다음에 ,(콤마)? : 1차원

In [10]:
array2 = numpy.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [11]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
array2.shape

(3, 4)

In [15]:
array1.size

12

In [16]:
array2.size

12

In [17]:
array3 = numpy.full(3,10)

In [18]:
print(array3)

[10 10 10]


* numpy.full(a,b) a의 갯수만큼 b를 넣음

In [19]:
array4 = numpy.full(6,0)
array5 = numpy.zeros(6, dtype = int)

In [20]:
print(array4)
print(array5)

[0 0 0 0 0 0]
[0 0 0 0 0 0]


In [21]:
array6 = numpy.ones(6, dtype= int)
print(array6)

[1 1 1 1 1 1]


In [22]:
array7 = numpy.random.random(10)
print(array7)

[0.3512712  0.1618664  0.50325623 0.04094725 0.97464931 0.81670813
 0.01058992 0.68143591 0.85138716 0.89503882]


In [23]:
array8 = numpy.arange(10)
print(array8)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
array9 = numpy.arange(1,8)
print(array9)

[1 2 3 4 5 6 7]


In [26]:
array10 = numpy.arange(3,17,3)
print(array10)

[ 3  6  9 12 15]


* arange(n,m,s) :  return  between 'n' to 'm -1' , having gap 's' each numbers 